## Lists, Dictionaries and Sets in Python

## Part 1

### Lists in Python

Sequences in Python are data structures that hold objects in an ordered array. Now, we will work on Lists, the most common sequence data types in Python.

In [21]:
#Example 
l1 = ['learning', "Python", 'is fun?', True]
print(l1)

['learning', 'Python', 'is fun?', True]


List can also be created by using list() function. 

In [22]:
#Example
l2 = list(("learning", "for", "life", True))
print(l2)

['learning', 'for', 'life', True]


Adding to an existing list

### Question 1

Add 10 to list l1 given above.

[ **Hint: ** Use **append** ]

In [7]:
l1 = ['learning', "Python", 'is fun?', True]
l1.append("10")
print(l1)

['learning', 'Python', 'is fun?', True, '10']


Removing from an existing list

### Question 2

Remove 10 from l1.

[ **Hint:** Use **remove**]

In [8]:
l1 = ['learning', "Python", 'is fun?', True, '10' ]
l1.remove("10")
print(l1)

['learning', 'Python', 'is fun?', True]


Joining 2 lists

### Question 3

[ **Hint: ** Use **+** operator or **extend**]

In [2]:
l1 = ['learning', "Python", 'is fun?', True]
l2 = list(("learning", "for", "life", True))

In [5]:
print (l1)
l1.extend(l2)
print (l1)

['learning', 'Python', 'is fun?', True, 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g']
['learning', 'Python', 'is fun?', True, 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 'l', 'e', 'a', 'r', 'n', 'i', 'n', 'g', 'learning', 'for', 'life', True]


Number List

### Question 4

Find Range and Mean of l3.

l3 = [2,4,6,8]

[ **Hint: ** Use **len(),sum(), min(), max()** functions ]
 
If you want to use standard functions like mean & range, you have to import them from numpy else you can calculate them the traditional way using formulas

In [14]:
l3 = [2,4,6,8]
print('Range of l3 is:', max(l3) - min(l3))

Range of l3 is: 6


In [15]:
l3 = [2,4,6,8]
print('Mean of l3 is:', sum(l3) / len(l3))

Mean of l3 is: 5.0


Count the occurances of an element in a given list.

### Question 5
Append the given sequence of numbers to l3 (given above) 0,1,3,3,5,5,7,9. Count the occurences of 5 in l3.

[ **Hint: ** Use ** + operator to add multiple elements in the array and count() function to print the occurences**]

In [4]:
l3 = [2,4,6,8]
print("Print before append:" , l3)
l3.extend([0, 1, 3, 3, 5, 5, 7, 9])
print("Print after append:" , l3)
print("Occurences of 5 in l3:" ,l3.count(5))

Print before append: [2, 4, 6, 8]
Print after append: [2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]
Occurences of 5 in l3: 2


Sorting and Reversing a list

### Question 6
sort and print l3 in ascending and descending order sequentially (given above)

**(Hint: Use .sort() function)**

In [13]:
l3 = [2,4,6,8]
l3.extend([0, 1, 3, 3, 5, 5, 7, 9])
print("Before sort:" , l3)
l3.sort()
print(l3)
print("After sort:Ascending:" , l3)
print(l3)
l3.sort(reverse=True)
print("After sort:Descending:" , l3)

Before sort: [2, 4, 6, 8, 0, 1, 3, 3, 5, 5, 7, 9]
[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]
After sort:Ascending: [0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 3, 4, 5, 5, 6, 7, 8, 9]
After sort:Descending: [9, 8, 7, 6, 5, 5, 4, 3, 3, 2, 1, 0]


### Functions

**Example:**

**def** function_name(args)**:**
    
    function code goes here

### Question 7

Define a function with name **sum_3** which can take 3 numbers as input, and returns sum of them.

In [18]:
def  sum_3(a=0,b=0,c=0):
    sum=a+b+c;
    return sum;

num1=5
num2=55
num3=35
print("The sum is",sum_3(num1,num2,num3))

The sum is 95


### Lambda Functions

Anonymous functions or no name functions, which can be considered when you use a function only once.

**Example:**

f = lambda x, y : x + y

f(1,1)

2


### Question 8

Write the same above **sum_3** function using lambda.

In [19]:
f = lambda x, y, z : x + y + z
f(5,55,35)

95

# Numpy

We have seen python basic data structures in our last section. They are great but lack specialized features for data analysis. Like, adding roows, columns, operating on 2d matrices aren't readily available. So, we will use *numpy* for such functions.



In [28]:
import numpy as np

Numpy operates on *nd* arrays. These are similar to lists but contains homogenous elements but easier to store 2-d data.

In [22]:
l1 = [1,2,3,4]
nd1 = np.array(l1)
print(nd1)

l2 = [5,6,7,8]
nd2 = np.array([l1,l2])
print(nd2)

[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]


Sum functions on np.array()

In [20]:
print(nd2.shape)

print(nd2.size)

print(nd2.dtype)

(2L, 4L)
8
int32


### Question 1

Create an identity 2d-array or matrix (with ones across the diagonal).

[ **Hint: ** You can also use **np.identity()** function ]

In [26]:
 np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Question 2

Create a 2d-array or matrix of order 3x3 with values = 9,8,7,6,5,4,3,2,1 arranged in the same order.

Use: **np.matrix()** function



In [33]:
mtx = np.matrix('9 8 7;6 5 4;3 2 1')
print(mtx)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Question 3

Reverse both the rows and columns of the given matrix.

Hint: You can use the transpose **.T**)

In [40]:
mtx = np.matrix('9 8 7;6 5 4;3 2 1')
print("Matrix:\n", mtx)
print("Tranpose Matrix:\n", np.transpose(mtx))


Matrix:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Tranpose Matrix:
 [[9 6 3]
 [8 5 2]
 [7 4 1]]


### Question 4
Add + 1 to all the elements in the given matrix.

In [49]:
mtx = np.matrix('9 8 7;6 5 4;3 2 1')
mtx1 = np.matrix('1 1 1;1 1 1;1 1 1')
print("Matrix:\n", mtx)
print ("Matrix with + 1:\n", mtx + 1)
print ("Matrix with + 1:\n", np.add(mtx,mtx1))

Matrix:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Matrix with + 1:
 [[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
Matrix with + 1:
 [[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]


Similarly you can do operations like scalar  substraction, division, multiplication (operating on each element in the matrix)

### Question 5

Find the mean of all elements in the given matrix nd6.
nd6 = [[  1   4   9 121 144 169]
 [ 16  25  36 196 225 256]
 [ 49  64  81 289 324 361]]
 
 Use: **.mean()** function


In [51]:
nd6 = np.matrix('1 4 9 121 144 169;16 25 36 196 225 256; 49 64 81 289 324 361')
print(np.mean(nd6))

131.66666666666666


### Question 7

Find the dot product of two given matrices.

[**Hint:** Use **np.dot()**]

In [53]:
mtx = np.matrix('9 8 7;6 5 4;3 2 1')
mtx1 = np.matrix('1 1 1;1 1 1;1 1 1')
print(np.dot(mtx,mtx1))

[[24 24 24]
 [15 15 15]
 [ 6  6  6]]


# Pandas

We have seen Numpy in the last section. It is good at performing math operation on 2d-arrays of numbers. But the major drawback is, it cannot deal with heterogenous values. So, Pandas dataframes are helpful in that aspect for storing different data types and referring the values like a dict in python instead of just referring each item with index.

[Link to Official Documentation](http://pandas.pydata.org/pandas-docs/version/0.23/dsintro.html)

## Series

Pandas series are almost same as nd arrays in numpy, with a additional inferencing ability with custom labels like *keys* in a *dictionary* in python.

In [88]:
import numpy as np
import pandas as pd

In [64]:
#Example

series1 = pd.Series(data = [1,2,3], index = ['key1', 'key2', 'key3'])
series1

key1    1
key2    2
key3    3
dtype: int64

### Question 1

Convert a given dict to pd series.

[**Hint:** Use **.Series**]

In [65]:
d1 = {'a': 1, 'b': 2, 'c': 3}

In [66]:
d2=pd.Series(d1)
print(d2)

a    1
b    2
c    3
dtype: int64


You can directly use numpy functions on series.
### Question 2

Find the dot product of both the series create above


[ **Hint: ** Use **np.dot()** ]

In [67]:
print(np.dot(series1,d2))

14


## Dataframes

A dataframe is a table with labeled columns which can hold different types of data in each column. 

In [90]:
# Example
d1 = {'a': [1,2,3], 'b': [3,4,5], 'c':[6,7,8] }
df1 = pd.DataFrame(d1)
df1

a  b  c
0  1  3  6
1  2  4  7
2  3  5  8

### Question 3

Select second row in the above dataframe df1.



In [77]:
print(df1.loc[1])

a    2
b    4
c    7
Name: 1, dtype: int64


### Question 4

Select column c in second row of df1.

[ **Hint: ** For using labels use **df.loc[row, column]**. For using numeric indexed use **df.iloc[]**. For using mixture of numeric indexes and labels use **df.ix[row, column]** ]



In [80]:
print(df1['b'])

0    3
1    4
2    5
Name: b, dtype: int64


## Using Dataframes on a dataset

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors 

In [86]:
## Reading a dataset from a csv file using pandas.
mtcars = pd.read_csv('mtcars.csv')
mtcars.index = mtcars['name']


Following questions are based on analysing a particular dataset using dataframes.

### Question 5

Check the type and dimensions of given dataset - mtcars.


[ **Hint: ** Use **type()** and **df.shape** ]

In [92]:
print("Type:", type(mtcars))
print("Dimensions:", mtcars.shape)

Type: <class 'pandas.core.frame.DataFrame'>
Dimensions: (32, 12)


### Question 6

Check the first 10 lines and last 10 lines of the given dataset- mtcars.

[**Hint:** Use **.head()** and **.tail()**]

In [94]:
print("\nTop 10 lines:\n", mtcars.head())
print("\nLast 10 lines:\n", mtcars.tail())


Top 10 lines:
                 name   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2  

Last 10 lines:
               name   mpg  cyl   disp   hp  drat     wt  qsec  vs  am  gear  \
27    Lotus Europa  30.4    4   95.1  113  3.77  1.513  16.9   1   1     5   
28  Ford Pantera L  15.8    8  351.0  264  4.22  3.170  14.5   0   1     5   
29    Ferrari Dino  19.7    6  145.0  175  3.62  2.770  15.5   0   1     5   
30   Maserati Bora  15.0    8  301.0  335  3.54  3.570  14.6   0   1     5   
31      Volvo 142E  21.4    4 

### Question 7

Print all the column labels in the given dataset - mtcars.

[ **Hint: ** Use **df.columns** ]

In [96]:
print(mtcars.columns)

Index(['name', 'mpg', 'cyl', 'disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am',
       'gear', 'carb'],
      dtype='object')


### Question 8

Select first 6 rows and 3 columns in mtcars dataframe.

**Hint: **  
mtcars.ix[:,:] gives all rows and columns in the dataset.

In [102]:
print(mtcars.ix[:6,:3])

                name   mpg  cyl
0          Mazda RX4  21.0    6
1      Mazda RX4 Wag  21.0    6
2         Datsun 710  22.8    4
3     Hornet 4 Drive  21.4    6
4  Hornet Sportabout  18.7    8
5            Valiant  18.1    6
6         Duster 360  14.3    8


C:\Users\Amigo\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


## Lab Brief - Statistical Learning with Python

### Part-1

## Measures of Data

Descriptive Statistcs are measures that summarize important features of data. Producing these descriptive statistics is a common first step to take after cleaning and preparing a dataset for further analysis. Examples are like calculating Mean or Median. In this lab, we will be looking into some of these functions and explore several new ones.

#### Measures of Central Tendency

Whenever you measure things of the same kind, a fairly large number of such measurements will tend to cluster around the middle value. Such a value is called a measure of "Central Tendency". The other terms that are used synonymously are "Measures of Location", or "Statistical Averages". 

In [103]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

mtcars = pd.read_csv('mtcars.csv')

##### Using the mtcars dataset.

For the below set of questions, we will be using the cars data from [Motor Trend Car Road Tests](http://stat.ethz.ch/R-manual/R-devel/library/datasets/html/mtcars.html)

The data was extracted from the 1974 Motor Trend US magazine, and comprises fuel consumption and 10 aspects of automobile design and performance for 32 automobiles (1973–74 models). 


Details :
    
A data frame with 32 observations on 11 (numeric) variables.

[, 1] 	mpg 	Miles/(US) gallon

[, 2] 	cyl 	Number of cylinders

[, 3] 	disp 	Displacement (cu.in.)

[, 4] 	hp 	Gross horsepower

[, 5] 	drat 	Rear axle ratio

[, 6] 	wt 	Weight (1000 lbs)

[, 7] 	qsec 	1/4 mile time

[, 8] 	vs 	Engine (0 = V-shaped, 1 = straight)

[, 9] 	am 	Transmission (0 = automatic, 1 = manual)

[,10] 	gear 	Number of forward gears

[,11] 	carb 	Number of carburetors 

#### Explore the data - Setting the index

In [170]:
mtcars.index = mtcars["name"]
mtcars.head()
# mtcars.mean() #By default this will give the mean of each column

name   mpg  cyl   disp   hp  drat     wt  \
name                                                                       
Mazda RX4                  Mazda RX4  21.0    6  160.0  110  3.90  2.620   
Mazda RX4 Wag          Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875   
Datsun 710                Datsun 710  22.8    4  108.0   93  3.85  2.320   
Hornet 4 Drive        Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215   
Hornet Sportabout  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440   

                    qsec  vs  am  gear  carb  
name                                          
Mazda RX4          16.46   0   1     4     4  
Mazda RX4 Wag      17.02   0   1     4     4  
Datsun 710         18.61   1   1     4     1  
Hornet 4 Drive     19.44   1   0     3     1  
Hornet Sportabout  17.02   0   0     3     2

### Question 1

What is the first car name given in mtcars?

** Make use of index which has been set previously **

**Hint**: Use .loc function


In [181]:
print(mtcars.iloc[ 0 ,0])

Mazda RX4


### Question 2
What is the highest difference between the hp and cyl?

**Hint:** You can use **max()** function to find the difference

In [142]:
mtcars[["hp", "cyl"]].max(axis=0)

hp     335
cyl      8
dtype: int64

### Question 3
What are the cars having highest weight(wt) and lowest weight(wt)?

**Hint:** Use idxmax() and idxmin() to locate the row

Use **.iloc** function to print the  row

**Note:** Both idxmax and idxmin belong to pandas

In [131]:
mtcars[["wt"]].max(axis = 0)
mtcars.loc[mtcars['wt'].idxmax()]

name    Lincoln Continental
mpg                    10.4
cyl                       8
disp                    460
hp                      215
drat                      3
wt                    5.424
qsec                  17.82
vs                        0
am                        0
gear                      3
carb                      4
Name: Lincoln Continental, dtype: object

In [134]:
mtcars.loc[mtcars['wt'].idxmin()]

Lotus Europa


name    Lotus Europa
mpg             30.4
cyl                4
disp            95.1
hp               113
drat            3.77
wt             1.513
qsec            16.9
vs                 1
am                 1
gear               5
carb               2
Name: Lotus Europa, dtype: object

### Question 4

Find the mean of each row and each column in the given dataset.

**Hint:** Use .mean() function. To operate on rows use **axis=0**, on columns use **axis=1**

In [144]:
print(mtcars.mean(axis=0))
print(mtcars.mean(axis=1))

mpg      20.090625
cyl       6.187500
disp    230.721875
hp      146.687500
drat      3.596563
wt        3.217250
qsec     17.848750
vs        0.437500
am        0.406250
gear      3.687500
carb      2.812500
dtype: float64
name
Mazda RX4              29.907273
Mazda RX4 Wag          29.981364
Datsun 710             23.598182
Hornet 4 Drive         38.739545
Hornet Sportabout      53.664545
Valiant                35.049091
Duster 360             59.720000
Merc 240D              24.634545
Merc 230               27.233636
Merc 280               31.860000
Merc 280C              31.787273
Merc 450SE             46.430909
Merc 450SL             46.500000
Merc 450SLC            46.350000
Cadillac Fleetwood     66.232727
Lincoln Continental    66.058545
Chrysler Imperial      65.972273
Fiat 128               19.440909
Honda Civic            17.742273
Toyota Corolla         18.814091
Toyota Corona          24.888636
Dodge Challenger       47.240909
AMC Javelin            46.007727
Camaro Z28  

### Question 5

Plot mpg values of mtcards dataframe using matplotlib.

**Hint: Use plt.plot function**

In [154]:
plt.plot(x='mpg')

AttributeError: 'DataFrame' object has no attribute 'plt'

## Part 2

## Measures of Dispersion

Measures of Dispersion (Spread) are statistics that describe how data varies. Measure of dispersion gives us the sense of how much the data tends to diverge from the central tendency.

### Question 6

What the range of `mpg` in the given dataset?

**Hint:** Range = max-min

In [182]:
print(mtcars[["mpg"]].max(axis=0)- mtcars[["mpg"]].min(axis=0))

mpg    23.5
dtype: float64


### Question 7

Calculate the 25th quantile (lower quantile)for `mpg` in the given dataset.

**Hint:** Use **.quantile()**

In [165]:
mtcars.quantile(.25, axis = 1)

name
Mazda RX4              3.2600
Mazda RX4 Wag          3.3875
Datsun 710             1.6600
Hornet 4 Drive         2.0000
Hornet Sportabout      2.5000
Valiant                1.8800
Duster 360             3.1050
Merc 240D              2.5950
Merc 230               2.5750
Merc 280               3.6800
Merc 280C              3.6800
Merc 450SE             3.0000
Merc 450SL             3.0000
Merc 450SLC            3.0000
Cadillac Fleetwood     2.9650
Lincoln Continental    3.0000
Chrysler Imperial      3.1150
Fiat 128               1.6000
Honda Civic            1.8075
Toyota Corolla         1.4175
Toyota Corona          1.7325
Dodge Challenger       2.3800
AMC Javelin            2.5000
Camaro Z28             3.3650
Pontiac Firebird       2.5000
Fiat X1-9              1.4675
Porsche 914-2          2.0700
Lotus Europa           1.7565
Ford Pantera L         3.5850
Ferrari Dino           3.1950
Maserati Bora          3.5550
Volvo 142E             2.3900
Name: 0.25, dtype: float64

### Question 8

Calculate the Inter-Quartile Range(IQR) for `mpg` in the given dataset.

Interquartile range (IQR) is another common measure of spread. IQR is the distance between the 3rd quartile and the 1st quartile.

**Hint:** IQR = Q3 - Q1

### Question 9

Calculate the Variance, Standard Deviation and Median Absolute Deviation for `mpg`.

Variance and Standard Deviation are two other common measure of dispersion.

**Hint:** Use .var() and .std()

**Hint:** Median Absolute Deviation - alternative measure of spread based on the median. It is the median of the absolute value of the deviations from the median. 

In [188]:
print("Variance:", mtcars[["mpg"]].var())
print("Standard Deviation:", mtcars[["mpg"]].std())
series = pd.Series(mtcars) 
  
# calling .mad() method 
mtcars.mad('mpg',axis = 1)  


Variance: mpg    36.324103
dtype: float64
Standard Deviation: mpg    6.026948
dtype: float64


ValueError: Wrong number of items passed 12, placement implies 32